### ISSUE TITLE
How to add the config.js

### ISSUE THREAD

**Issue by r-meertens** [danshapir/ember-export-config#1]
Hi,

How do I add this config.js to the index.html?

I have tried `<script src="assets/config.js"></script>` in app/index.html, but this isn't working.

vendor.js:173Uncaught Error: Could not find module `webappConfig/config/environment` imported from `(require)`

Thanks for the good work :)

Cheers,
Rick

**Comment by henderikus** [comment]
I fixed it by putting the line between the script tags who includes vendor.js and my webapp.js

```
        <script src="assets/vendor.js"></script>
        <script src="assets/config.js"></script>
        <script src="assets/webapp.js"></script>
```
I have also put the line in my tests.html, but my tests are still broken.
It looks like the problem is with Mirage. 

Any ideas?

**Comment by danshapir** [comment]
@henderikus I just saw your message - how did it work in the end?

**Comment by r-meertens** [comment]
I needed to add it after line `<script src="assets/vendor.js"></script>`

**Comment by danshapir** [comment]
Just like the example in the dummy app. Great :smile:

**Comment by r-meertens** [comment]
Haha.. ok thanks.. I didn't see that coming :)

I looked at the dummy app and i think  the following code in environment.js isn't going to work, because it will be 'stringified' :(  : 

```
if (environment === 'test') {
    // Testem prefers this...
    ENV.baseURL = '/';
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
}
```

**Comment by r-meertens** [comment]
The workaround to keep my IF statements working in 'environment.js' is to enable the Ember_Export_Config addon only in the production build. I need them to ONLY enable my 'mirage-addon' in the test environment..

```
  //ember-cli-build.js
  //Only enable ember-export-config in the production build.
  isProdBuild = EmberApp.env() === 'production';
  var app = new EmberApp(defaults, {
    storeConfigInMeta: !isProdBuild,
    'ember-export-config': { enabled: isProdBuild }
  });

```

```
  //environment.js
  //Enable mirage in the test environment.
  if (environment === 'test') {
    ENV.baseURL = '/';
    ENV.locationType = 'none';

    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';

    ENV['ember-cli-mirage'] = {
      enabled: true
    }
  }
  if (environment === 'production') {
  }

```

Danshapir, I'am interested in your opinion about this workaroung of mine.

Cheers!
